#!/bin/sh

if [ ! -d $SNAP/kf5/usr ]; then
  runtime="kde-frameworks-5-core18"
  slot="kde-frameworks-5-core18:kde-frameworks-5-core18-slot"

  echo "You need to connect this snap to the $runtime snap."
  echo ""
  echo "You can do this with those commands:"
  echo "snap install $runtime"
  echo "snap refresh $runtime"
  echo "snap connect $SNAP_NAME:kde-frameworks-5-plug $slot"
  exit 1
fi

exec telegram-desktop "$@"