name: 🐞 Bug report
description: Report errors or unexpected behavior.
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      placeholder: Tell us what should happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
      placeholder: Tell us what happens instead
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      description: |
        Write exact OS (e.g. Windows 11, macOS 14, Ubuntu 24.04 GNOME).
        * 🛑 NO KERNEL VERSIONS (uname)
    validations:
      required: true
  - type: input
    attributes:
      label: Version of Telegram Desktop
      description: |
        Write EXACT version number (e.g. 5.1.2).
        * 🛑 DO NOT WRITE "LATEST". We will instantly close the issue.
        * 🛑 LINUX REPO VERSIONS ARE NOT SUPPORTED. Go to your distro's tracker (unless you are the distro maintainer).
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation source
      multiple: false
      options:
        - Downloaded from desktop.telegram.org or GitHub
        - Microsoft Store
        - Mac App Store
        - Flatpak
        - Snap
        - Linux package manager (apt, dnf, pacman, etc)
        - Other source
    validations:
      required: true
  - type: input
    attributes:
      label: Crash ID
      description: |
        If the app crashed, we need a Crash ID.
        1. Go to Settings -> Advanced
        2. Enable "Install beta versions"
        3. Reproduce the crash
        4. Copy the Crash ID on next launch
  - type: textarea
    attributes:
      label: Logs
      description: >
        Type the word `viewlogs`
        [directly into your settings menu](https://github.com/telegramdesktop/tdesktop/wiki/Cheat-Codes)
        to open the logs folder.
      placeholder: Insert log.txt here
      render: shell
