#############################################################################
# Makefile for building: ../Mac/DebugEmoji/MetaEmoji.app/Contents/MacOS/MetaEmoji
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  MetaEmoji.pro
# Template: app
# Command: /usr/local/Qt-5.3.0/bin/qmake -spec macx-xcode -o MetaEmoji.xcodeproj/project.pbxproj MetaEmoji.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /usr/local/Qt-5.3.0/bin/qmake
MetaEmoji.xcodeproj/project.pbxproj: MetaEmoji.pro /usr/local/Qt-5.3.0/mkspecs/macx-clang/qmake.conf /usr/local/Qt-5.3.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.3.0/mkspecs/qdevice.pri \
		/usr/local/Qt-5.3.0/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.3.0/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.3.0/mkspecs/common/unix.conf \
		/usr/local/Qt-5.3.0/mkspecs/common/mac.conf \
		/usr/local/Qt-5.3.0/mkspecs/common/macx.conf \
		/usr/local/Qt-5.3.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.3.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Qt-5.3.0/mkspecs/common/clang.conf \
		/usr/local/Qt-5.3.0/mkspecs/common/clang-mac.conf \
		/usr/local/Qt-5.3.0/mkspecs/qconfig.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_cocoaprintersupport.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qcocoa.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qcorewlanbearer.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qdds.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qdeclarativeview.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qicns.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qico.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qjp2.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qminimal.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmng.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qqt7engine.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qsqlite.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qsvg.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtga.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtiff.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtsensors_dummy.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qwbmp.pri \
		/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qwebp.pri \
		/usr/local/Qt-5.3.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.3.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Qt-5.3.0/mkspecs/macx-xcode/qmake.conf \
		/usr/local/Qt-5.3.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-5.3.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/c++11.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/qt.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/resources.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/moc.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/mac/rez.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.3.0/mkspecs/features/lex.prf \
		MetaEmoji.pro \
		/usr/local/Qt-5.3.0/lib/libQt5Gui_debug.prl \
		/usr/local/Qt-5.3.0/lib/libQt5Core_debug.prl \
		/usr/local/Qt-5.3.0/lib/libqtharfbuzzng_debug.prl \
		/usr/local/Qt-5.3.0/plugins/platforms/libqcocoa_debug.prl \
		/usr/local/Qt-5.3.0/lib/libQt5PrintSupport_debug.prl \
		/usr/local/Qt-5.3.0/lib/libQt5Widgets_debug.prl \
		/usr/local/Qt-5.3.0/lib/libQt5PlatformSupport_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqdds_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqicns_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqico_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqjp2_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqmng_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqtga_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqtiff_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqwbmp_debug.prl \
		/usr/local/Qt-5.3.0/plugins/imageformats/libqwebp_debug.prl
	$(QMAKE) -spec macx-xcode -o MetaEmoji.xcodeproj/project.pbxproj MetaEmoji.pro
/usr/local/Qt-5.3.0/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.3.0/mkspecs/qdevice.pri:
/usr/local/Qt-5.3.0/mkspecs/features/device_config.prf:
/usr/local/Qt-5.3.0/mkspecs/common/shell-unix.conf:
/usr/local/Qt-5.3.0/mkspecs/common/unix.conf:
/usr/local/Qt-5.3.0/mkspecs/common/mac.conf:
/usr/local/Qt-5.3.0/mkspecs/common/macx.conf:
/usr/local/Qt-5.3.0/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.3.0/mkspecs/common/gcc-base-mac.conf:
/usr/local/Qt-5.3.0/mkspecs/common/clang.conf:
/usr/local/Qt-5.3.0/mkspecs/common/clang-mac.conf:
/usr/local/Qt-5.3.0/mkspecs/qconfig.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_cocoaprintersupport.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qavfcamera.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qcocoa.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qcorewlanbearer.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qdds.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qdeclarativeview.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qicns.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qico.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qjp2.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qminimal.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qmng.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qoffscreen.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qqt7engine.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qsqlite.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qsvg.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qsvgicon.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtaccessiblequick.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtga.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtiff.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtsensors_dummy.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qwbmp.pri:
/usr/local/Qt-5.3.0/mkspecs/modules/qt_plugin_qwebp.pri:
/usr/local/Qt-5.3.0/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.3.0/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.3.0/mkspecs/macx-clang/qmake.conf:
/usr/local/Qt-5.3.0/mkspecs/macx-xcode/qmake.conf:
/usr/local/Qt-5.3.0/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt-5.3.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.3.0/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.3.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt-5.3.0/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.3.0/mkspecs/features/default_post.prf:
/usr/local/Qt-5.3.0/mkspecs/features/mac/sdk.prf:
/usr/local/Qt-5.3.0/mkspecs/features/mac/default_post.prf:
/usr/local/Qt-5.3.0/mkspecs/features/c++11.prf:
/usr/local/Qt-5.3.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt-5.3.0/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.3.0/mkspecs/features/qt.prf:
/usr/local/Qt-5.3.0/mkspecs/features/resources.prf:
/usr/local/Qt-5.3.0/mkspecs/features/moc.prf:
/usr/local/Qt-5.3.0/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.3.0/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.3.0/mkspecs/features/mac/rez.prf:
/usr/local/Qt-5.3.0/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.3.0/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.3.0/mkspecs/features/yacc.prf:
/usr/local/Qt-5.3.0/mkspecs/features/lex.prf:
MetaEmoji.pro:
/usr/local/Qt-5.3.0/lib/libQt5Gui_debug.prl:
/usr/local/Qt-5.3.0/lib/libQt5Core_debug.prl:
/usr/local/Qt-5.3.0/lib/libqtharfbuzzng_debug.prl:
/usr/local/Qt-5.3.0/plugins/platforms/libqcocoa_debug.prl:
/usr/local/Qt-5.3.0/lib/libQt5PrintSupport_debug.prl:
/usr/local/Qt-5.3.0/lib/libQt5Widgets_debug.prl:
/usr/local/Qt-5.3.0/lib/libQt5PlatformSupport_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqdds_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqicns_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqico_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqjp2_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqmng_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqtga_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqtiff_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqwbmp_debug.prl:
/usr/local/Qt-5.3.0/plugins/imageformats/libqwebp_debug.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o MetaEmoji.xcodeproj/project.pbxproj MetaEmoji.pro

qmake_all: FORCE

