name: Windows macOS-UI

on:
  push:
    branches: [macos-ui]
  workflow_dispatch:

jobs:
  windows:
    name: Windows x64
    runs-on: windows-latest
    timeout-minutes: 360

    env:
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"

    defaults:
      run:
        shell: cmd

    steps:
      - name: Prepare directories.
        run: |
          mkdir %userprofile%\TBuild\Libraries
          mklink /d %GITHUB_WORKSPACE%\TBuild %userprofile%\TBuild
          echo TBUILD=%GITHUB_WORKSPACE%\TBuild>>%GITHUB_ENV%
          echo LibrariesPath=%GITHUB_WORKSPACE%\TBuild\Libraries\win64>>%GITHUB_ENV%

      - name: Get repository name.
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone.
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: ${{ env.TBUILD }}\${{ env.REPO_NAME }}

      - name: First set up.
        shell: bash
        run: |
          DOCPATH=$TBUILD/$REPO_NAME/docs/building-win.md
          SDK="$(grep "SDK version" $DOCPATH | sed -r 's/.*\*\*(.*)\*\* SDK version.*/\1/')"
          echo "SDK=$SDK" >> $GITHUB_ENV

          echo "$(sha256sum $TBUILD/$REPO_NAME/$PREPARE_PATH | awk '{ print $1 }')" >> CACHE_KEY.txt
          echo "$SDK" >> CACHE_KEY.txt
          echo "CACHE_KEY=$(sha256sum CACHE_KEY.txt | awk '{ print $1 }')" >> $GITHUB_ENV

          git config --global user.email "you@example.com"
          git config --global user.name "Sample"

      - uses: Eden-CI/msvc-dev-cmd@master
        name: Native Tools Command Prompt.
        with:
          arch: x64
          sdk: ${{ env.SDK }}
          toolset: "14.44"

      - name: NuGet sources.
        run: |
          nuget sources Disable -Name "Microsoft Visual Studio Offline Packages"
          nuget sources Add -Source https://api.nuget.org/v3/index.json & exit 0

      - name: ThirdParty cache.
        id: cache-third-party
        uses: actions/cache@v4
        with:
          path: ${{ env.TBUILD }}\ThirdParty
          key: ${{ runner.OS }}-x64-third-party-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-third-party-

      - name: Libraries cache.
        id: cache-libs
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.LibrariesPath }}\*
            !${{ env.LibrariesPath }}\cache_keys
            !${{ env.LibrariesPath }}\[qQ]t[_-]*
            ${{ env.LibrariesPath }}\cache_keys\*
          key: ${{ runner.OS }}-x64-libs-v2-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-libs-v2-

      - name: Qt cache.
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.LibrariesPath }}\[qQ]t[_-]*
            ${{ env.LibrariesPath }}\cache_keys\[qQ]t[_-]*
          key: ${{ runner.OS }}-x64-qt-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-qt-

      - name: Libraries.
        run: |
          %TBUILD%\%REPO_NAME%\Telegram\build\prepare\win.bat skip-release silent

      - name: Free up some disk space.
        shell: bash
        run: find $LibrariesPath '(' '(' ! '(' -name '*.lib' -o -name '*.a' -o -name '*.exe' -o -name '*.h' -o -name '*.hpp' -o -name '*.inc' -o -name '*.cmake' -o -name '*.pc' -o -path '*/include/*' -o -path '*/objects-*' -o -path '*/cache_keys/*' -o -path '*/patches/*' -o -path '*/nv-codec-headers/*' ')' -type f ')' -o -empty ')' -delete

      - name: Telegram Desktop build.
        run: |
          cd %TBUILD%\%REPO_NAME%\Telegram

          call configure.bat ^
          x64 ^
          -D TDESKTOP_API_TEST=ON ^
          -D CMAKE_CONFIGURATION_TYPES=Debug ^
          -D CMAKE_COMPILE_WARNING_AS_ERROR=OFF ^
          -D CMAKE_MSVC_DEBUG_INFORMATION_FORMAT= ^
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF ^
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON

          cmake --build ..\out --config Debug --parallel

      - name: Move artifact.
        run: |
          set OUT=%TBUILD%\%REPO_NAME%\out\Debug
          mkdir artifact
          move %OUT%\Telegram.exe artifact/
          if exist %OUT%\Updater.exe move %OUT%\Updater.exe artifact/

      - uses: actions/upload-artifact@v4
        name: Upload artifact.
        with:
          name: Telegram-macOS-UI-Windows-x64
          path: artifact\
          retention-days: 14
