name: Needs user action.

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 2 * * *'

jobs:
  needs-user-action:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          responseRequiredLabel: needs user action
