name: Waiting for answer.

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '30 0 * * *'

jobs:
  waiting-for-answer:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          responseRequiredLabel: waiting for answer
