name: Telegram Python - Windows x64 Qt6 Release

on:
  push:
    branches:
      - python-plugins

  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows-x64:
    name: Windows x64 Qt6 Release
    runs-on: windows-latest
    timeout-minutes: 360

    env:
      PREPARE_PATH: Telegram/build/prepare/prepare.py

    defaults:
      run:
        shell: cmd

    steps:

      # ------------------------------------------------------------
      # Prepare build directories
      # ------------------------------------------------------------

      - name: Prepare directories
        run: |
          mkdir %userprofile%\TBuild
          mkdir %userprofile%\TBuild\Libraries
          mklink /d %GITHUB_WORKSPACE%\TBuild %userprofile%\TBuild

          echo TBUILD=%GITHUB_WORKSPACE%\TBuild>>%GITHUB_ENV%
          echo LibrariesPath=%GITHUB_WORKSPACE%\TBuild\Libraries\win64>>%GITHUB_ENV%
